"""initial schema

Revision ID: 863eeffd73fd
Revises: 
Create Date: 2026-05-03 18:04:26.119415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863eeffd73fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_api_keys', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_email', 'organizations', ['email'], unique=False)
    op.create_index('idx_org_is_active', 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_organization_id', 'documents', ['organization_id'], unique=False)
    op.create_index('idx_doc_processed', 'documents', ['is_processed'], unique=False)
    op.create_index('idx_doc_verified_active', 'documents', ['is_verified', 'is_active'], unique=False)
    op.create_index(op.f('ix_documents_is_active'), 'documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_documents_is_processed'), 'documents', ['is_processed'], unique=False)
    op.create_index(op.f('ix_documents_is_verified'), 'documents', ['is_verified'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLINICIAN', 'PATIENT', 'ORGANIZATION_OWNER', name='roleenum'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_email')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_apikey_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_apikey_expires', 'api_keys', ['expires_at'], unique=False)
    op.create_index('idx_apikey_organization_id', 'api_keys', ['organization_id'], unique=False)
    op.create_index('idx_apikey_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('action', sa.Enum('USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_ROLE_CHANGED', 'API_KEY_CREATED', 'API_KEY_REVOKED', 'RATE_LIMIT_UPDATED', 'DOCUMENT_UPLOADED', 'DOCUMENT_DELETED', 'ORGANIZATION_UPDATED', name='auditactionenum'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_organization_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunk_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunk_organization_id', 'document_chunks', ['organization_id'], unique=False)
    op.create_index('idx_chunk_vector_id', 'document_chunks', ['vector_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_vector_id'), 'document_chunks', ['vector_id'], unique=True)
    op.create_table('queries',
    sa.Column('question', sa.String(length=2000), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('intent', sa.Enum('DIAGNOSIS', 'TREATMENT', 'DRUG_INFO', 'SYMPTOM_CHECK', 'GENERAL', name='queryintentenum'), nullable=True),
    sa.Column('top_k_retrieved', sa.Integer(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_organization_id', 'queries', ['organization_id'], unique=False)
    op.create_index('idx_query_query_id', 'queries', ['query_id'], unique=False)
    op.create_index('idx_query_session_id', 'queries', ['session_id'], unique=False)
    op.create_index('idx_query_user_id', 'queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_queries_organization_id'), 'queries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_queries_query_id'), 'queries', ['query_id'], unique=True)
    op.create_index(op.f('ix_queries_session_id'), 'queries', ['session_id'], unique=False)
    op.create_index(op.f('ix_queries_user_id'), 'queries', ['user_id'], unique=False)
    op.create_table('query_analytics',
    sa.Column('question', sa.String(length=2000), nullable=False),
    sa.Column('answer_length', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_created_at', 'query_analytics', ['created_at'], unique=False)
    op.create_index('idx_analytics_organization_id_created', 'query_analytics', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_analytics_user_id_created', 'query_analytics', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_query_analytics_organization_id'), 'query_analytics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_query_analytics_user_id'), 'query_analytics', ['user_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('requests_per_day', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ratelimit_organization_id', 'rate_limits', ['organization_id'], unique=False)
    op.create_index('idx_ratelimit_user_id', 'rate_limits', ['user_id'], unique=False)
    op.create_index(op.f('ix_rate_limits_organization_id'), 'rate_limits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rate_limits_user_id'), 'rate_limits', ['user_id'], unique=True)
    op.create_table('query_feedback',
    sa.Column('feedback_type', sa.Enum('HELPFUL', 'NOT_HELPFUL', 'PARTIALLY_HELPFUL', 'MISLEADING', 'OUTDATED', name='queryfeedbackenum'), nullable=False),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_query_id', 'query_feedback', ['query_id'], unique=False)
    op.create_index('idx_feedback_type', 'query_feedback', ['feedback_type'], unique=False)
    op.create_index('idx_feedback_user_id', 'query_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_query_feedback_feedback_type'), 'query_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_query_feedback_query_id'), 'query_feedback', ['query_id'], unique=True)
    op.create_index(op.f('ix_query_feedback_user_id'), 'query_feedback', ['user_id'], unique=False)
    op.create_table('query_sources',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'chunk_id', name='uq_query_chunk')
    )
    op.create_index('idx_source_chunk_id', 'query_sources', ['chunk_id'], unique=False)
    op.create_index('idx_source_query_id', 'query_sources', ['query_id'], unique=False)
    op.create_index(op.f('ix_query_sources_chunk_id'), 'query_sources', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_query_sources_query_id'), 'query_sources', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_sources_query_id'), table_name='query_sources')
    op.drop_index(op.f('ix_query_sources_chunk_id'), table_name='query_sources')
    op.drop_index('idx_source_query_id', table_name='query_sources')
    op.drop_index('idx_source_chunk_id', table_name='query_sources')
    op.drop_table('query_sources')
    op.drop_index(op.f('ix_query_feedback_user_id'), table_name='query_feedback')
    op.drop_index(op.f('ix_query_feedback_query_id'), table_name='query_feedback')
    op.drop_index(op.f('ix_query_feedback_feedback_type'), table_name='query_feedback')
    op.drop_index('idx_feedback_user_id', table_name='query_feedback')
    op.drop_index('idx_feedback_type', table_name='query_feedback')
    op.drop_index('idx_feedback_query_id', table_name='query_feedback')
    op.drop_table('query_feedback')
    op.drop_index(op.f('ix_rate_limits_user_id'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_organization_id'), table_name='rate_limits')
    op.drop_index('idx_ratelimit_user_id', table_name='rate_limits')
    op.drop_index('idx_ratelimit_organization_id', table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_query_analytics_user_id'), table_name='query_analytics')
    op.drop_index(op.f('ix_query_analytics_organization_id'), table_name='query_analytics')
    op.drop_index('idx_analytics_user_id_created', table_name='query_analytics')
    op.drop_index('idx_analytics_organization_id_created', table_name='query_analytics')
    op.drop_index('idx_analytics_created_at', table_name='query_analytics')
    op.drop_table('query_analytics')
    op.drop_index(op.f('ix_queries_user_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_session_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_query_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_organization_id'), table_name='queries')
    op.drop_index('idx_query_user_id', table_name='queries')
    op.drop_index('idx_query_session_id', table_name='queries')
    op.drop_index('idx_query_query_id', table_name='queries')
    op.drop_index('idx_query_organization_id', table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_document_chunks_vector_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('idx_chunk_vector_id', table_name='document_chunks')
    op.drop_index('idx_chunk_organization_id', table_name='document_chunks')
    op.drop_index('idx_chunk_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_organization_id', table_name='audit_logs')
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index('idx_apikey_user_id', table_name='api_keys')
    op.drop_index('idx_apikey_organization_id', table_name='api_keys')
    op.drop_index('idx_apikey_expires', table_name='api_keys')
    op.drop_index('idx_apikey_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_organization_id', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_verified'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_processed'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_active'), table_name='documents')
    op.drop_index('idx_doc_verified_active', table_name='documents')
    op.drop_index('idx_doc_processed', table_name='documents')
    op.drop_index('idx_doc_organization_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_index('idx_org_is_active', table_name='organizations')
    op.drop_index('idx_org_email', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
