"""add invite_code to organizations

Revision ID: eb2e3faeed4f
Revises: 863eeffd73fd
Create Date: 2026-05-11 13:14:08.701374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2e3faeed4f'
down_revision: Union[str, None] = '863eeffd73fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('invite_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_organizations_invite_code'), 'organizations', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_invite_code'), table_name='organizations')
    op.drop_column('organizations', 'invite_code')
    # ### end Alembic commands ###
